### ISSUE TITLE
400 page is in lists of pages

### ISSUE THREAD

**Issue by danielfdickinson** [bowman2001/perplexdoc#23]
This can be avoided easily (while still leaving it rendered for an actual 400 Not Found situation) by adding:

```yaml
_build:
  list: never
```

to the frontmatter of the `400/index.md` file.

It probably should also be excluded from search, but I'm not sure how to do that yet.

**Comment by bowman2001** [comment]
I’ve added the snippet to the frontmatter, thanks. And I’ve tested, if the page appears in the Pagefind search: It doesn’t and I guess Pagefind is already taking care of this.
