### ISSUE TITLE
Arbitrary icons for social and follow links

### ISSUE THREAD

**Issue by bowman2001** [bowman2001/perplexdoc#24]
I noticed that the social and follow icons only allow one to use branded targets. It would be great to be able to use custom (non-Simple) icons for follow and contact where they don't fit into a 'brand'. (@danielfdickinson)

**Comment by bowman2001** [comment]
See update on https://perplex.desider.at/doc/site/navigation

**Comment by danielfdickinson** [comment]
Thank you!
